import React from 'react'

export default function TermsCondition() {
  return (
      <section className="pb-16 bg-blur">
          <div className="container mx-auto px-7">
              <div className="px-3 border-b border-greyb pb-2 mb-10">
                  <div>
                      <h1 className="text-dblack text-2xl font-bold">Terms & Conditions</h1>
                  </div>
              </div>
             
      <div class="td-fix-index">
     <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>
           ASIAN TRADE PUBLICATIONS LIMITED<br/>
            GARAVI GUJARAT PUBLICATIONS LIMITED<br/>
              ADVERTISING TERMS AND CONDITIONS<br/>
                  All Advertisements are accepted subject to the conditions of insertion set out below.</p>
                  <p className='font-bold' >1. ORDERING</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>1.1 By placing an order for the insertion of an Advertisement in the <strong>Magazine</strong> or on the Web Site the Buyer confirms its acceptance of and agreement to these terms and conditions (“Conditions”) and the provisions of the attached Rate Card (or applicable Rate Card) which shall be deemed to be incorporated into these Conditions. In the event of any variation or inconsistency between these Conditions and the provisions of the applicable Rate Card, these Conditions shall prevail.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>1.2 These Conditions (with such variations, if any, as the Company may expressly agree in writing) shall apply to each contract for the placing of an Advertisement to the exclusion of any other terms and conditions including without limitation any terms or conditions which the Buyer purports to apply under any purchase order, confirmation of order, specification or other document.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>1.3 In placing an order for the insertion of an Advertisement, the Buyer offers to contract with the Company as principal even where the Buyer is not the Advertiser notwithstanding that the Buyer shall in doing so bind the Advertiser for which the Buyer is acting as agent. A legally binding contract is formed only upon the Company’s acceptance of that offer. No order shall be deemed to be accepted by the Company until confirmed by the Company [in writing].</p>
                  <p className='text-dblack  font-bold text-base leading-[30px] mb-5 wow fadeInDown'> 2. BUYER’S INDEMNITY AND WARRANTIES
                  </p>
                  <p>
                  2.1 The Buyer accepts full legal responsibility in respect of any Advertisement submitted by it for publication and indemnifies the Company and shall keep the Company fully and effectively indemnified against any actions, proceedings, claims, demands, damages, costs (including legal costs) and any other liability whatsoever (whether civil or criminal) arising directly or indirectly and whether or not reasonably foreseeable from (a) the Company’s handling, publication or reproduction of the Advertisement, and/or (b) any breach by the Buyer of any of its obligations, warranties or representations contained in these Conditions or implied by law.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>2.2 Without prejudice to the generality of the foregoing, the Buyer warrants and represents that:<br/>
                  2.2.1 The Advertisement does not contravene any Act of Parliament in the United Kingdom, law of the European Union, rule of any statutorily recognized regulatory authority, or any other relevant legislation or code of practice;</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>2.2.2 In the case of any Advertisement which amounts to a Financial Promotion the Advertiser is, or the contents of the Advertisement have been approved by, an Authorized Person or the Advertisement is otherwise permitted under and complies in all respects with the FSMA;</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>2.2.3 The publication, republication and reproduction of the Advertisement (whether or not amended in accordance with Condition 3.4) in any medium (including without limitation in the <strong>Magazine</strong>, on the Web Site or in any Archive) will not (a) infringe any Rights of any third party, (b) breach any contract, agreement or understanding, (c) be in any way contrary to the law applicable anywhere in the world, or (d) otherwise expose the Company to the risk of any civil or criminal proceedings whatsoever;</p>
                    <br/>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>2.2.4 In respect of any Advertisement which contains the name and/or image of any living person, the Buyer has obtained the authority of such person to make use of their name and/or image;</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>2.2.5 No contamination file, virus, worm or Trojan horse is contained within or will originate from the Advertisement, its content or any linked area or from any e-mail, attachment, message or other documentation supplied to the Company by the Buyer;</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>2.2.6 The Advertisement is legal, decent, honest and truthful and does not infringe the British Codes of Advertising and Sales Promotion or any other relevant codes under the supervision of the Advertising Standards Authority or other relevant regulatory body; and</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>2.2.7 Where it is acting as an advertising agency or media buyer, or in some other representative capacity, the Buyer is authorized by the Advertiser to place the Advertisement in accordance with these Conditions.</p>
                  <p className='text-dblack font-bold text-base leading-[30px] mb-5 wow fadeInDown'>3 SUPPLY OF PROOFS AND CORRECTIONS</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>3.1 The Advertisement and all artwork, copy, photographs, copy instructions, proofs and other material necessary for the publication of the Advertisement (together the “Materials”) must be received by the Company in such form as the Company may specify [by the latest date specified in the Rate Card][not less than 7 clear Days prior to the Publication Date].</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>3.2 If the Materials are not received by the date or in the form specified in Condition 3.1, the Company reserves the right (at its sole discretion), and without prejudice to the Company’s right to be paid for the relevant Advertisement either (a) to print the relevant Advertisement from any copy or proofs previously supplied by the Advertiser (or, if different, the Buyer), or (b) not to publish the relevant Advertisement.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>3.3 The Company cannot undertake to make, nor shall it be responsible for, any alterations or corrections to the Advertisement if requested after the latest date specified for such alterations or corrections in the Rate Card. [The Company will endeavor to provide the Buyer with proofs of an Advertisement prior to publication where reasonably practicable, but cannot guarantee to do so.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>3.4 The Company may (without prejudice to the Buyer’s warranties contained in these Conditions) make or require the Buyer to make any amendments, corrections or alterations to an Advertisement that the Company considers in its absolute discretion necessary or desirable, whether to conform with the style and subject matter of the Publication, to comply with the Buyer’s warranties in these Conditions or the technical specifications specifications set out in the applicable Rate Card, for legal or regulatory reasons or otherwise.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>4 MATERIALS</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>4.1 The Company shall not be liable for any loss of or damage to the Materials. Unless otherwise agreed in writing, the Company reserves the right to return at the Buyer’s expense or dispose of such Materials if not collected within six months of their receipt by the Company.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>4.2 The Buyer acknowledges that the Rights in all artwork, copy and other materials which the Company or its employees or its contractors has originated or re-worked shall vest solely in the Company.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>5 COMPANY RESPONSIBILITIES</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>5.1 The Company will use its reasonable endeavors to comply with the wishes of the Buyer in relation to the placing of the Advertisement in the Publication. Notwithstanding the foregoing, the Company cannot guarantee and does not warrant:</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>5.1.1 The Publication Date, the wording or the quality of color or mono reproduction of the Advertisement;</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>5.1.2 That the Advertisement will not back onto or face another advertisement or appear in the same issue or on the same page as another advertisement for the same or any similar product or service;</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>5.1.3 That the Advertisement will be placed in any special position unless agreed in writing by the Company in advance and for an additional charge. Any such agreement by the Company will be specific to an identified Advertiser, and no other Advertiser may take the agreed position without the Company’s prior written consent.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>5.2 The Buyer acknowledges and agrees that the Company shall use its reasonable endeavors to ensure the accuracy of any estimated figures relating to (a) the number, proportion or type of people likely to be exposed to the Advertisement (whether in the <strong>Magazine</strong>, on the Web Site or otherwise); (b) the number of exposures each person is likely to receive; and (c) the cost of achieving those exposures. Since these are matters which are ultimately beyond the Company’s control, no warranties can be given by the Company as to the accuracy of such estimates or as to the figures actually occurring and no liability shall attach to the Company in respect of any losses suffered by the Buyer or any third party by reason of the Buyer’s reliance on such estimates. The Buyer further acknowledges, in relation to any Advertisement to be published on the Web Site, that the Web Site will not be continuously available and will be subject to suspension from time to time for routine maintenance and updating.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>6 CANCELLATIONS</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>6.1 The Company reserves the right without giving prior notice to the Buyer (a) to postpone, suspend, transfer or cancel the publication of the Advertisement, and/or (b) to change the position of the Advertisement in the Publication. Provided that the Buyer is not in breach of any of these Conditions the Company will in such cases return any money paid by the Buyer in respect of any Advertisement which does not appear in the Publication.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>6.2 At the time an order is placed by the Buyer, if the Buyer is an advertising agency ormedia buyer and does not disclose (a) the name of its Advertiser client, and/or (b) the goods or services which are to be the subject of the Advertisement for that space, the Company may at any time refuse to accept or suspend the Advertisement, and in such circumstances neither the Buyer not the Advertiser shall have any claim against the Company in respect of such refusal or suspension, and if the space is not filled by the Company, the Buyer shall be responsible for any loss suffered by the Company.<br/>
                  6.3 The Company will only accept a request from the Buyer to postpone, suspend, transfer or cancel the publication of an Advertisement if the request is received in writing by the Company before [the latest date specified in the Rate Card]. Any such requests after that deadline shall not affect the Buyer’s liability for payment for the Advertisement. The Company may treat as a cancellation the fact that the Buyer is unable to pay its debts within the meaning of section 123 of the Insolvency Act 1986 prior to payment in full of the price for the relevant Advertisement or is otherwise in breach of any of these Conditions.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>7 ERRORS</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>7.1 If there is an error in the Advertisement as published or publication is delayed or does not occur as planned, the Company will not be liable unless this is caused by its neglect or default.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>7.2 The Buyer shall notify the Company in writing of any error in a published Advertisement as soon as practicable and in any event within [three] Days of its first publication. The Company shall not be liable for the repetition of an error in an Advertisement not drawn to its attention in accordance with this Condition 7.2.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>8 RATES AND PAYMENT</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>Unless the Company agrees otherwise in writing:</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.1 The price for any Advertisement will be the Rate Card price prevailing at the Publication Date. A 10% discount will be given for advance payment.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.2 Payment is due at the time the Buyer places its order for insertion of the Advertisement[ or within 15 days from the date of invoice following publication].</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.3 The Buyer acknowledges the cost to the Company of late payment of the Company’s invoices and accordingly agrees to pay in respect of any payment not made by the due date the aggregate of:-</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.3.1 an administration fee of £151; and</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.3.2 interest (accruing on a daily basis) on the amount unpaid at the rate of 4 per cent above the base rate for the time being of Barclays Bank Plc from the due date for payment up to the date on which the Company receives the full outstanding amount together with all interest.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.3.3 The Company reserves the right to charge the Buyer for the cost of the Company’s (or its printers’) extra production work arising from any exceptional production requirements or any acts or defaults of the Buyer (including without limitation amendments, corrections or alterations made pursuant to Condition 3.4 above).</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.4 The Company shall not provide any voucher copies of the <strong>Magazine</strong> for each insertion.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>8.5 VAT will be included and itemized separately on Company invoices, where appropriate, at the rate prevailing from time to time, the rate on the Rate Card being exclusive of VAT.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>9 ENTIRE AGREEMENT</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>9.1 These Conditions, read together with the Rate Card, constitute the entire agreement and understanding of the parties and supersedes any previous agreement between the parties relating to the placing of Advertisements by the Company. The Buyer agrees that it has not been induced to enter into these Conditions in reliance upon any warranty, representation, statement, agreement or undertaking of any kind (whether negligently or innocently made) of any person other than as expressly set out in these Conditions as a warranty. The only remedy available to the Buyer for breach of the said warranties shall be for breach of contract under the terms of these Conditions and the parties unconditionally and irrevocably waive any other claims, rights or remedies that may otherwise be available.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>10 LIMITATION OF LIABILITY</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>Subject always to Condition 13.4:-</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>10.1 The Company shall not be liable for any indirect or consequential loss (including without limitation business interruption and loss of profits, business, goodwill, reputation, anticipated savings, information or data) whether arising out of breach of contract, tort (including negligence), breach of statutory duty or otherwise howsoever; and</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>10.2 The Company’s total liability in contract, tort (including negligence), breach of statutory duty or otherwise howsoever arising in connection with the performance or contemplated performance of these Conditions shall be limited to (a) the refund of its charge for the relevant Advertisement, or (in the Company’s absolute discretion) (b) the free repeat publication of the relevant Advertisement or an appropriate corrective advertisement.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>11 FORCE MAJEURE</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>11.1 The Company shall not be liable for any failure to publish the Advertisement or perform any of its other obligations under these Conditions caused by circumstances beyond its reasonable control (including without limitation a labor dispute between a third party and its employees or an act of terrorism or military action).</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>12 DATA PROTECTION</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>12.1 The Buyer shall comply with the Data Protection Act 1998 and all associated legislation. The provision by the Buyer of mail, telephone, fax, e-mail or other contact details to the Company shall be deemed to constitute the Buyer’s consent to the Company’s use of that information to send the Buyer information about special advertising rates and features that the Company may offer from time to time. The Company may monitor and record telephone calls and e-mails for the Buyer’s protection and to ensure quality of service.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>13 MISCELLANEOUS</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>13.1 Reference to an act or omission of the Buyer shall include any act or omission of any relevant director, employee or agent of the Buyer.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>13.2 Reference to any Act of Parliament or Code of Practice shall be deemed to include reference to such Act or Code as amended, updated, re-enacted or replaced from time to time, as well as any subsidiary legislation, regulations or statutory instruments enacted under any such Act.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>13.3 No variation to these Conditions shall be valid unless it is in writing and signed by or on behalf of each of the parties.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>13.4 Nothing in these Conditions shall operate to limit or exclude any liability for fraud or for death or personal injury caused by the negligence of the Company or any other person for whose actions the Company is responsible or for any other liability to the extent that such liability may not be excluded or limited as a matter of law.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>13.5 The Buyer shall pay all monies which are payable by it to the Company without any right of set off, abatement, deduction, discount or withholding in respect of monies which are due from the Company or alleged to be due from the Company to the Buyer (or, if different, the Advertiser).</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>13.6 No person who is not a party to these Conditions has any right under the Contracts (Rights of Third Parties) Act 1999 or otherwise howsoever to enforce any term of these Conditions.</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>13.7 These Conditions shall be governed and construed in accordance with the laws of England and each party agrees to submit to the exclusive jurisdiction of the English Courts.</p>
                  <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown font-bold'>14 INTERPRETATION</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>14.1 In these Conditions unless the context otherwise requires reference to the singular includes reference to the plural (and vice versa) reference to any gender includes reference to the other genders and the following capitalized expressions shall have the following respective meanings and all other capitalized expressions have the meaning ascribed to them elsewhere in these Conditions:-</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>“Advertisement(s)” shall include any loose or insert advertisement, any advertisement attached to or distributed with the <strong>Magazine</strong>(including free gifts), information supplied in connection with an advertisement, and advertisements in any form (including without limitation electronic readable form on the Web Site);</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>“Advertiser” shall mean the person advertising its products or services or making an announcement in the Advertisement;<br/>
                  “Archive” shall mean any database in which the Company retains for future reference or use by itself or others material (including Advertisements) which has been published in or with the  <strong>Magazine</strong>or the Web Site;</p>
              <p className='text-dblack text-base leading-[30px] mb-5 wow fadeInDown'>“Authorized Person” shall have the meaning set out in section 31 of the FSMA;<br/>
                  “Buyer” shall mean the person placing an order for the insertion of an Advertisement with the Company, whether or not that person is the Advertiser;<br/>
                      “Company” shall mean Asian Trade Publications Ltd, Registered in England 1716184 at No.1 Silex Street, London SE1 0DW;<br/>
                          “Day(s)” shall mean any day except for a Saturday, Sunday or a day which is a public holiday in England and Wales;<br/>
                              “Financial Promotion” means any Advertisement that comprises or includes an invitation or inducement to engage in investment activity (as those terms are from time to time interpreted for the purposes of the FSMA);<br/>
                                  “FSMA” means the Financial Services and Markets Act 2000 together with any rules, orders, regulations, codes of practice and delegated legislation made thereunder from time to time;<br/>
                                      “Magazine” means each periodical printed publication published by the Company, including Garavi Gujarat. GG2, Asian Trader, Pharmacy Business, Asian Hospitality, Coupon Book and GG2 Jobs;<br/>
                                          “Publication” means the relevant issue of the <strong>Magazine</strong> or, as the context requires, the relevant period of publication of the Web Site;<br/>
                                              “Rate Card” means the Company’s current rate card in respect of the <strong>Magazine</strong>  or the Web Site including, without limitation, advertising rates and additional conditions concerning copy and cancellation dates, technical and stylistic specifications and any related information;<br/>
                                                  “Rights” means any copyright, extended or revived copyright, design right, registered design right, patent, performer’s property right, trade mark, database right, image right, moral right or any similar right exercisable in any part of the world; and<br/>
                                                      “Web Site” means each and every web site owned or operated by the Company, including www.gg2.net , www.asiantrader.biz, www.pharmacy.biz, www.amg.biz</p>
                                                  <p>Requests to reuse our content are now being processed through PLSclear. Please visit www.plsclear.com to complete your permission request.</p>
                                              </div>
          </div>
      </section>
  )
}
